function mret = disp_biomarker_info(struct)
mret = ['Selected Peaks: ' num2str(struct.peaks_count) '/' ...
    num2str(struct.all_peaks_count)...
    ' - Limit: '...
    num2str(struct.cut_line)];

end