function [mret, params] = ga_fr_selected_intensities(tr_selector,gen,sins,data,cross_validation_rate,run_background)
disp('gaFRSelectedIntensities');

[mret, params] = ga_fr(tr_selector,...
    data.class,...
    data.selected_i,...
    gen,...
    sins,...
    cross_validation_rate,...
    run_background);
mret.transform.preprocess_params = [];
mret.transform.preprocess = @(data,params) data.selected_i;
mret.transform.name = [mret.transform.name ' (gaFRSelectedIntensities)'];

end