function [mret,params] = ga_fr_all_intensities(tr_selector,gen,sins,data,cross_validation_rate,run_background)
disp('gaFRAllIntensities')


[mret, params] = ga_fr(tr_selector,...
                    data.class,...
                    data.all,...
                    gen,...
                    sins,...
                    cross_validation_rate,run_background);
mret.transform.preprocess = @(data,params) data.all;
mret.transform.name = [mret.transform.name ' (gaFRAllIntensities)'];

end