function [mret,params, xpop] = ga_fr_selected_x(tr_selector,gen,sins,data,cross_validation_rate,run_background)
disp('gaFRselectedX')

[mret,params] = ga_fr(tr_selector,...
    data.class,...
    data.selected_mz,...
    gen,...
    sins,...
    cross_validation_rate,...
    run_background);
%mret.transform.data_type = obj.S_MZ;
mret.transform.preprocess_params = [];
mret.transform.preprocess = @(data,params) data.selected_mz;
mret.transform.name = [mret.transform.name ' (gaFRselectedX)'];
end
