apiVersion: v1
kind: Service
metadata:
  name: mlms-worker
  labels:
    app: mlms-worker
spec:
  type: ClusterIP
  selector:
    app: mlms-worker
  ports:
    - name: http
      port: 8080
      targetPort: http
