function [ mret ] = plot_options( option )
%PLOT_OPTIONS Summary of this function goes here
%   Detailed explanation goes here
colors = {'ob' 'oy' 'oc' 'or' 'om' 'ok'...
        'hb' 'hy' 'hc' 'hr' 'hm' 'hk'...
        'pb' 'py' 'pc' 'pr' 'pm' 'pk'...
        'ob' 'oy' 'oc' 'or' 'om' 'ok'...
        'db' 'dy' 'dc' 'dr' 'dm' 'dk'...
        '*b' '*y' '*c' '*r' '*m' '*k'...
        '+b' '+y' '+c' '+r' '+m' '+k'...
        'xb' 'xy' 'xc' 'xr' 'xm' 'xk'...
        'sb' 'sy' 'sc' 'sr' 'sm' 'sk'...
        'vb' 'vy' 'vc' 'vr' 'vm' 'vk'...
        '>b' '>y' '>c' '>r' '>m' '>k'...
        };
    mret = colors{option};

end

